"""master resume and cards

Revision ID: 9ea2b1a40b4e
Revises: 10d63519012b
Create Date: 2026-06-28 16:15:49.740860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea2b1a40b4e'
down_revision: Union[str, Sequence[str], None] = '10d63519012b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_resumes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('basic_info', sa.JSON(), nullable=False),
    sa.Column('parsed_from_file_url', sa.String(length=1024), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_resumes_user_id'), 'master_resumes', ['user_id'], unique=True)
    op.create_table('ability_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('master_resume_id', sa.Uuid(), nullable=False),
    sa.Column('skill_name', sa.String(length=128), nullable=False),
    sa.Column('evidence_text', sa.String(length=2048), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('last_used_year', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_weak', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['master_resume_id'], ['master_resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ability_cards_master_resume_id'), 'ability_cards', ['master_resume_id'], unique=False)
    op.create_table('experience_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('master_resume_id', sa.Uuid(), nullable=False),
    sa.Column('company_encrypted', sa.String(length=1024), nullable=False),
    sa.Column('period', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=512), nullable=False),
    sa.Column('achievements', sa.JSON(), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['master_resume_id'], ['master_resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_cards_master_resume_id'), 'experience_cards', ['master_resume_id'], unique=False)
    op.create_table('project_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('master_resume_id', sa.Uuid(), nullable=False),
    sa.Column('project_name', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('period', sa.String(length=64), nullable=False),
    sa.Column('scale_data', sa.JSON(), nullable=False),
    sa.Column('star', sa.JSON(), nullable=False),
    sa.Column('tech_stack', sa.JSON(), nullable=False),
    sa.Column('domain_tags', sa.JSON(), nullable=False),
    sa.Column('is_weak', sa.Boolean(), nullable=False),
    sa.Column('weak_reasons', sa.JSON(), nullable=False),
    sa.Column('cross_domain_translation', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['master_resume_id'], ['master_resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_cards_master_resume_id'), 'project_cards', ['master_resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_cards_master_resume_id'), table_name='project_cards')
    op.drop_table('project_cards')
    op.drop_index(op.f('ix_experience_cards_master_resume_id'), table_name='experience_cards')
    op.drop_table('experience_cards')
    op.drop_index(op.f('ix_ability_cards_master_resume_id'), table_name='ability_cards')
    op.drop_table('ability_cards')
    op.drop_index(op.f('ix_master_resumes_user_id'), table_name='master_resumes')
    op.drop_table('master_resumes')
    # ### end Alembic commands ###
