"""application and job_posting

Revision ID: 2eab1c955ff8
Revises: 281027aa5137
Create Date: 2026-06-28 19:29:11.056710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eab1c955ff8'
down_revision: Union[str, Sequence[str], None] = '281027aa5137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFTING', 'ARCHIVED', 'APPLIED', 'INTERVIEWING', 'OFFERED', 'REJECTED', name='application_status_enum'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('job_postings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('company_name', sa.String(length=256), nullable=False),
    sa.Column('job_title', sa.String(length=256), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('salary_range', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('requirements_parsed', sa.JSON(), nullable=False),
    sa.Column('hidden_preferences', sa.JSON(), nullable=False),
    sa.Column('red_flags', sa.JSON(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_application_id'), 'job_postings', ['application_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_postings_application_id'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
