"""application resource link

Revision ID: 56cfc4f34f9c
Revises: 2eab1c955ff8
Create Date: 2026-06-28 19:40:04.138608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56cfc4f34f9c'
down_revision: Union[str, Sequence[str], None] = '2eab1c955ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_resource_links',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('resource_item_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('application_id', 'resource_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_resource_links')
    # ### end Alembic commands ###
