"""resume branch

Revision ID: 4864c6d99edc
Revises: 56cfc4f34f9c
Create Date: 2026-06-28 19:55:21.922669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4864c6d99edc'
down_revision: Union[str, Sequence[str], None] = '56cfc4f34f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_branches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('version_label', sa.String(length=16), nullable=False),
    sa.Column('based_on_master_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('patch', sa.JSON(), nullable=False),
    sa.Column('ai_reasoning', sa.JSON(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('exported_pdf_urls', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_branches_application_id'), 'resume_branches', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_branches_application_id'), table_name='resume_branches')
    op.drop_table('resume_branches')
    # ### end Alembic commands ###
