"""resources

Revision ID: 8b4d0cdc158e
Revises: 4864c6d99edc
Create Date: 2026-06-29 00:03:05.479926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4d0cdc158e'
down_revision: Union[str, Sequence[str], None] = '4864c6d99edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_collections_user_id'), 'resource_collections', ['user_id'], unique=False)
    op.create_table('resource_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('INTERVIEW_RECALL', 'COMPANY_INTEL', 'RECRUITER_BG', 'INDUSTRY_DOC', 'OTHER', name='resource_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=False),
    sa.Column('ai_extracted_signals', sa.JSON(), nullable=False),
    sa.Column('linked_company_names', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_items_type'), 'resource_items', ['type'], unique=False)
    op.create_index(op.f('ix_resource_items_user_id'), 'resource_items', ['user_id'], unique=False)
    op.create_table('resource_collection_links',
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['resource_collections.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_items.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'resource_id')
    )
    # ### end Alembic commands ###
    # 补 Plan 2 预留的 FK：application_resource_links.resource_item_id -> resource_items.id
    op.create_foreign_key(
        "fk_application_resource_links_resource_item_id",
        "application_resource_links",
        "resource_items",
        ["resource_item_id"],
        ["id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "fk_application_resource_links_resource_item_id",
        "application_resource_links",
        type_="foreignkey",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_collection_links')
    op.drop_index(op.f('ix_resource_items_user_id'), table_name='resource_items')
    op.drop_index(op.f('ix_resource_items_type'), table_name='resource_items')
    op.drop_table('resource_items')
    op.drop_index(op.f('ix_resource_collections_user_id'), table_name='resource_collections')
    op.drop_table('resource_collections')
    # ### end Alembic commands ###
