"""investment

Revision ID: ae759097399d
Revises: 8b4d0cdc158e
Create Date: 2026-06-29 00:20:30.517134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae759097399d'
down_revision: Union[str, Sequence[str], None] = '8b4d0cdc158e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('used_resume_branch_id', sa.Uuid(), nullable=True),
    sa.Column('action_type', sa.Enum('SUBMITTED', 'VIEWED', 'INTERVIEW_SCHEDULED', 'OFFER_RECEIVED', 'REJECTED', name='investment_action_enum'), nullable=False),
    sa.Column('action_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['used_resume_branch_id'], ['resume_branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_action_type'), 'investments', ['action_type'], unique=False)
    op.create_index(op.f('ix_investments_application_id'), 'investments', ['application_id'], unique=False)
    op.drop_constraint(op.f('fk_application_resource_links_resource_item_id'), 'application_resource_links', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_application_resource_links_resource_item_id'), 'application_resource_links', 'resource_items', ['resource_item_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_investments_application_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_action_type'), table_name='investments')
    op.drop_table('investments')
    # ### end Alembic commands ###
