"""weekly digest

Revision ID: 1ebe7b61a138
Revises: ae759097399d
Create Date: 2026-06-29 00:33:22.818185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ebe7b61a138'
down_revision: Union[str, Sequence[str], None] = 'ae759097399d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_digests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('week_of', sa.Date(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('ai_observation_text', sa.Text(), nullable=False),
    sa.Column('suggested_actions', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_of', name='uq_user_week')
    )
    op.create_index(op.f('ix_weekly_digests_user_id'), 'weekly_digests', ['user_id'], unique=False)
    op.create_index(op.f('ix_weekly_digests_week_of'), 'weekly_digests', ['week_of'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_digests_week_of'), table_name='weekly_digests')
    op.drop_index(op.f('ix_weekly_digests_user_id'), table_name='weekly_digests')
    op.drop_table('weekly_digests')
    # ### end Alembic commands ###
