"""coach inquiry

Revision ID: 77fa2ee59bab
Revises: 1ebe7b61a138
Create Date: 2026-06-29 00:52:54.744348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77fa2ee59bab'
down_revision: Union[str, Sequence[str], None] = '1ebe7b61a138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_inquiries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('source_screen', sa.String(length=64), nullable=False),
    sa.Column('contact_method', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'SCHEDULED', 'CONVERTED', 'DROPPED', name='coach_inquiry_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_inquiries_created_at'), 'coach_inquiries', ['created_at'], unique=False)
    op.create_index(op.f('ix_coach_inquiries_user_id'), 'coach_inquiries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coach_inquiries_user_id'), table_name='coach_inquiries')
    op.drop_index(op.f('ix_coach_inquiries_created_at'), table_name='coach_inquiries')
    op.drop_table('coach_inquiries')
    # ### end Alembic commands ###
